server:
  port: 8080
spring:
  application:
    name: fullTextSearch
  datasource:
    url: jdbc:mysql://localhost:3306/test_idx?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initialSize: 2
    minIdle: 5
    maxActive: 10